"""add deleted_at field for organization

Revision ID: 5ca36b2b00eb
Revises: fedfe6461ecb
Create Date: 2026-06-24 13:42:44.411556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca36b2b00eb'
down_revision: Union[str, Sequence[str], None] = 'fedfe6461ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'deleted_at')
    # ### end Alembic commands ###
