"""made is_new_user field in organization table nullable

Revision ID: b3723c5c532b
Revises: 6b159f8be92f
Create Date: 2026-07-01 07:27:46.141490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3723c5c532b'
down_revision: Union[str, Sequence[str], None] = '6b159f8be92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_invitations', 'is_new_user',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_invitations', 'is_new_user',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
