"""modifies org invitation model

Revision ID: c11bf5746499
Revises: 5ca36b2b00eb
Create Date: 2026-06-30 07:31:15.686091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11bf5746499'
down_revision: Union[str, Sequence[str], None] = '5ca36b2b00eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_invitations', sa.Column('is_used', sa.Boolean(), nullable=False))
    op.add_column('organization_invitations', sa.Column('used_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('organization_invitations', 'is_new_user',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_invitations', 'is_new_user',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('organization_invitations', 'used_at')
    op.drop_column('organization_invitations', 'is_used')
    # ### end Alembic commands ###
