"""intial migration

Revision ID: fedfe6461ecb
Revises: 
Create Date: 2026-06-21 09:20:33.589018

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fedfe6461ecb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_organizations_owner_id'), 'organizations', ['owner_id'], unique=False)
    op.create_table('organization_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('invitation_token', sa.String(), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=False),
    sa.Column('invited_user_email', sa.String(), nullable=False),
    sa.Column('invitation_status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', name='organizationinvitationstatusenum'), nullable=False),
    sa.Column('invited_for_role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='organizationroleenum'), nullable=False),
    sa.Column('is_new_user', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invitations_invitation_token'), 'organization_invitations', ['invitation_token'], unique=True)
    op.create_index(op.f('ix_organization_invitations_invited_by_id'), 'organization_invitations', ['invited_by_id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_invited_user_email'), 'organization_invitations', ['invited_user_email'], unique=False)
    op.create_index(op.f('ix_organization_invitations_org_id'), 'organization_invitations', ['org_id'], unique=False)
    op.create_index('uq_pending_invite_per_org_email', 'organization_invitations', ['org_id', 'invited_user_email'], unique=True, postgresql_where=sa.text("invitation_status = 'PENDING'"))
    op.create_table('organization_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='organizationroleenum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_memberships')
    op.drop_index('uq_pending_invite_per_org_email', table_name='organization_invitations', postgresql_where=sa.text("invitation_status = 'PENDING'"))
    op.drop_index(op.f('ix_organization_invitations_org_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_invited_user_email'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_invited_by_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_invitation_token'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index(op.f('ix_organizations_owner_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
